# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zh472S6jNRcLqO6mo2TkUPfa4HcE_S1L
"""

import pandas as pd
import random

records = []

for i in range(1000):

    age = random.randint(35,75)

    menopausal = "Post" if age > 50 else "Pre"

    er = random.choice(["Positive","Negative"])
    pr = random.choice(["Positive","Negative"])

    her2 = random.choices(
        ["Positive","Negative"],
        weights=[70,30]
    )[0]

    stage = random.choice(["III","IV"])

    if stage == "III":
        t_status = random.choice(["T3","T4"])
        n_status = random.choice(["N2","N3"])
        m_status = "M0"
    else:
        t_status = "T4"
        n_status = "N3"
        m_status = "M1"

    lymph_nodes = random.randint(12,25)

    necrosis = random.choice(["Medium","High"])

    histology = random.choice([
        "Ductal",
        "Lobular",
        "Mixed"
    ])

    location = random.choice([
        "Upper Outer",
        "Upper Inner",
        "Lower Outer",
        "Lower Inner"
    ])

    records.append([
        age,menopausal,er,pr,her2,
        stage,t_status,n_status,m_status,
        lymph_nodes,necrosis,histology,
        location,"Chemotherapy"
    ])

for i in range(1000):

    age = random.randint(40,80)

    menopausal = "Post"

    er = "Positive"
    pr = "Positive"

    her2 = "Negative"

    stage = random.choice(["I","II"])

    t_status = random.choice(["T1","T2"])

    n_status = random.choice(["N0","N1"])

    m_status = "M0"

    lymph_nodes = random.randint(0,8)

    necrosis = random.choice([
        "Low",
        "Medium"
    ])

    histology = random.choice([
        "Ductal",
        "Lobular",
        "Mixed"
    ])

    location = random.choice([
        "Upper Outer",
        "Upper Inner",
        "Lower Outer",
        "Lower Inner"
    ])

    records.append([
        age,menopausal,er,pr,her2,
        stage,t_status,n_status,m_status,
        lymph_nodes,necrosis,histology,
        location,"Hormonal Therapy"
    ])

for i in range(1000):

    age = random.randint(30,70)

    menopausal = random.choice([
        "Pre",
        "Post"
    ])

    er = random.choice([
        "Positive",
        "Negative"
    ])

    pr = random.choice([
        "Positive",
        "Negative"
    ])

    her2 = "Negative"

    stage = "I"

    t_status = "T1"

    n_status = "N0"

    m_status = "M0"

    lymph_nodes = random.randint(0,3)

    necrosis = "Low"

    histology = random.choice([
        "Ductal",
        "Lobular",
        "Mixed"
    ])

    location = random.choice([
        "Upper Outer",
        "Upper Inner",
        "Lower Outer",
        "Lower Inner"
    ])

    records.append([
        age,menopausal,er,pr,her2,
        stage,t_status,n_status,m_status,
        lymph_nodes,necrosis,histology,
        location,"Surgery"
    ])

columns = [
    "Age",
    "Menopausal_Status",
    "ER_Status",
    "PR_Status",
    "HER2_Status",
    "Cancer_Stage",
    "T_Status",
    "N_Status",
    "M_Status",
    "Lymph_Node_Count",
    "Tumor_Necrosis",
    "Histology_Type",
    "Tumor_Location",
    "Treatment"
]

df = pd.DataFrame(records, columns=columns)

df = df.sample(frac=1).reset_index(drop=True)

df.head()

df["Treatment"].value_counts()

import random

for idx in df.sample(frac=0.05).index:

    current = df.loc[idx, "Treatment"]

    if current == "Chemotherapy":

        if random.random() < 0.5:
            df.loc[idx, "Treatment"] = "Hormonal Therapy"
        else:
            df.loc[idx, "Treatment"] = "Surgery"

    elif current == "Hormonal Therapy":

        if random.random() < 0.5:
            df.loc[idx, "Treatment"] = "Chemotherapy"
        else:
            df.loc[idx, "Treatment"] = "Surgery"

    else:

        if random.random() < 0.5:
            df.loc[idx, "Treatment"] = "Chemotherapy"
        else:
            df.loc[idx, "Treatment"] = "Hormonal Therapy"

df["Treatment"].value_counts()

df.duplicated().sum()

df.shape

df = df.drop_duplicates()

df.sample(15)

from google.colab import files

files.download(
    "breast_cancer_treatment_dataset_v3_clean.csv"
)